//HintName: BinaryObjectsGenerator.g.cs
// <auto-generated/>
#nullable enable

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Values"/></term> <description>2 * 2</description> </item>
/// <item> <term> --- </term> <description>4</description> </item>
/// </list> </remarks>
[global::Darp.BinaryObjects.BinaryConstant(4)]
public sealed partial record Parent : global::Darp.BinaryObjects.IBinaryReadable<Parent>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 4)
            return false;
        var ___readValues = global::Darp.BinaryObjects.Generated.Utilities.ReadBinaryObjectArrayLittleEndian<ManualObject>(source[0..4], 2, out _);
        bytesRead += 4;

        value = new Parent(___readValues);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 4)
            return false;
        var ___readValues = global::Darp.BinaryObjects.Generated.Utilities.ReadBinaryObjectArrayBigEndian<ManualObject>(source[0..4], 2, out _);
        bytesRead += 4;

        value = new Parent(___readValues);
        return true;
    }
}

namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    [GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    file static class Utilities
    {
        /// <summary> Reads a <c>T[]</c> from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static T[] ReadBinaryObjectArrayLittleEndian<T>(ReadOnlySpan<byte> source, int elementLength, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            var numberOfElements = source.Length / elementLength;
            var array = new T[numberOfElements];
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadLittleEndian(source.Slice(i * elementLength, elementLength), out T? value, out var tempBytesRead))
                    throw new ArgumentException($"Could not read {typeof(T).Name} from source");
                array[i] = value;
            }
            bytesRead = numberOfElements * elementLength;
            return array;
        }
        /// <summary> Reads a <c>T[]</c> from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static T[] ReadBinaryObjectArrayBigEndian<T>(ReadOnlySpan<byte> source, int elementLength, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            var numberOfElements = source.Length / elementLength;
            var array = new T[numberOfElements];
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadBigEndian(source.Slice(i * elementLength, elementLength), out T? value, out var tempBytesRead))
                    throw new ArgumentException($"Could not read {typeof(T).Name} from source");
                array[i] = value;
            }
            bytesRead = numberOfElements * elementLength;
            return array;
        }
    }
}
