//HintName: BinaryObjectsGenerator.g.cs
// <auto-generated/>
#nullable enable

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Value"/></term> <description>1</description> </item>
/// <item> <term> --- </term> <description>1</description> </item>
/// </list> </remarks>
[global::Darp.BinaryObjects.BinaryConstant(1)]
public sealed partial record TestObjectNested : global::Darp.BinaryObjects.IBinaryObject<TestObjectNested>
{
    /// <inheritdoc />
    [global::System.Diagnostics.Contracts.Pure]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => 1;

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 1)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteBool(destination[0..1], this.Value);
        bytesWritten += 1;

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 1)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteBool(destination[0..1], this.Value);
        bytesWritten += 1;

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObjectNested? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObjectNested? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 1)
            return false;
        var ___readValue = global::Darp.BinaryObjects.Generated.Utilities.ReadBool(source[0..1]);
        bytesRead += 1;

        value = new TestObjectNested(___readValue);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObjectNested? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObjectNested? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 1)
            return false;
        var ___readValue = global::Darp.BinaryObjects.Generated.Utilities.ReadBool(source[0..1]);
        bytesRead += 1;

        value = new TestObjectNested(___readValue);
        return true;
    }
}

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Value1"/></term> <description>1 * 2</description> </item>
/// <item> <term><see cref="Value2"/></term> <description>1 * 2</description> </item>
/// <item> <term><see cref="Value3"/></term> <description>1 * 2</description> </item>
/// <item> <term> --- </term> <description>6</description> </item>
/// </list> </remarks>
[global::Darp.BinaryObjects.BinaryConstant(6)]
public sealed partial record TestObject : global::Darp.BinaryObjects.IBinaryObject<TestObject>
{
    /// <inheritdoc />
    [global::System.Diagnostics.Contracts.Pure]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => 6;

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 6 || this.Value1.Length < 2 || this.Value2.Length < 2 || this.Value3.Count < 2)
            return false;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanLittleEndian<TestObjectNested>(destination[0..2], this.Value1.Span, 1, out var ___bytesWrittenValue1))
        {
            bytesWritten += ___bytesWrittenValue1;
            return false;
        }
        bytesWritten += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanLittleEndian<TestObjectNested>(destination[2..4], this.Value2, 1, out var ___bytesWrittenValue2))
        {
            bytesWritten += ___bytesWrittenValue2;
            return false;
        }
        bytesWritten += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanLittleEndian<TestObjectNested>(destination[4..6], global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Value3), 1, out var ___bytesWrittenValue3))
        {
            bytesWritten += ___bytesWrittenValue3;
            return false;
        }
        bytesWritten += 2;

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 6 || this.Value1.Length < 2 || this.Value2.Length < 2 || this.Value3.Count < 2)
            return false;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanBigEndian<TestObjectNested>(destination[0..2], this.Value1.Span, 1, out var ___bytesWrittenValue1))
        {
            bytesWritten += ___bytesWrittenValue1;
            return false;
        }
        bytesWritten += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanBigEndian<TestObjectNested>(destination[2..4], this.Value2, 1, out var ___bytesWrittenValue2))
        {
            bytesWritten += ___bytesWrittenValue2;
            return false;
        }
        bytesWritten += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanBigEndian<TestObjectNested>(destination[4..6], global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Value3), 1, out var ___bytesWrittenValue3))
        {
            bytesWritten += ___bytesWrittenValue3;
            return false;
        }
        bytesWritten += 2;

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 6)
            return false;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectArrayLittleEndian<TestObjectNested>(source[0..2], 1, out var ___readValue1, out var ___bytesReadValue1))
        {
            bytesRead += ___bytesReadValue1;
            return false;
        }
        bytesRead += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectArrayLittleEndian<TestObjectNested>(source[2..4], 1, out var ___readValue2, out var ___bytesReadValue2))
        {
            bytesRead += ___bytesReadValue2;
            return false;
        }
        bytesRead += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectListLittleEndian<TestObjectNested>(source[4..6], 1, out var ___readValue3, out var ___bytesReadValue3))
        {
            bytesRead += ___bytesReadValue3;
            return false;
        }
        bytesRead += 2;
        value = new TestObject(___readValue1, ___readValue2, ___readValue3);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 6)
            return false;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectArrayBigEndian<TestObjectNested>(source[0..2], 1, out var ___readValue1, out var ___bytesReadValue1))
        {
            bytesRead += ___bytesReadValue1;
            return false;
        }
        bytesRead += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectArrayBigEndian<TestObjectNested>(source[2..4], 1, out var ___readValue2, out var ___bytesReadValue2))
        {
            bytesRead += ___bytesReadValue2;
            return false;
        }
        bytesRead += 2;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectListBigEndian<TestObjectNested>(source[4..6], 1, out var ___readValue3, out var ___bytesReadValue3))
        {
            bytesRead += ___bytesReadValue3;
            return false;
        }
        bytesRead += 2;
        value = new TestObject(___readValue1, ___readValue2, ___readValue3);
        return true;
    }
}

namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    [GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    file static class Utilities
    {
        /// <summary> Writes a <c>bool</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteBool(Span<byte> destination, bool value)
        {
            destination[0] = value ? (byte)0b1 : (byte)0b0;
        }
        /// <summary> Reads a <c>bool</c> from the given source </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ReadBool(ReadOnlySpan<byte> source)
        {
            return source[0] > 0;
        }
        public static bool TryWriteBinaryObjectSpanLittleEndian<T>(Span<byte> destination, ReadOnlySpan<T> value, int elementLength, out int bytesWritten)
            where T : IBinaryWritable
        {
            bytesWritten = 0;
            var numberOfElements = Math.Min(value.Length, destination.Length / elementLength);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!value[i].TryWriteLittleEndian(destination.Slice(i * elementLength, elementLength), out var itemBytesWritten))
                {
                    bytesWritten += itemBytesWritten;
                    return false;
                }
                bytesWritten += elementLength;
            }
            return true;
        }
        public static bool TryWriteBinaryObjectSpanBigEndian<T>(Span<byte> destination, ReadOnlySpan<T> value, int elementLength, out int bytesWritten)
            where T : IBinaryWritable
        {
            bytesWritten = 0;
            var numberOfElements = Math.Min(value.Length, destination.Length / elementLength);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!value[i].TryWriteBigEndian(destination.Slice(i * elementLength, elementLength), out var itemBytesWritten))
                {
                    bytesWritten += itemBytesWritten;
                    return false;
                }
                bytesWritten += elementLength;
            }
            return true;
        }
        public static bool TryReadBinaryObjectArrayLittleEndian<T>(ReadOnlySpan<byte> source, int elementLength, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T[]? value, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            value = null;
            bytesRead = 0;
            var numberOfElements = source.Length / elementLength;
            var result = new T[numberOfElements];
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadLittleEndian(source.Slice(i * elementLength, elementLength), out var item, out var itemBytesRead))
                {
                    bytesRead += itemBytesRead;
                    return false;
                }
                bytesRead += elementLength;
                result[i] = item;
            }
            value = result;
            return true;
        }
        public static bool TryReadBinaryObjectArrayBigEndian<T>(ReadOnlySpan<byte> source, int elementLength, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T[]? value, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            value = null;
            bytesRead = 0;
            var numberOfElements = source.Length / elementLength;
            var result = new T[numberOfElements];
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadBigEndian(source.Slice(i * elementLength, elementLength), out var item, out var itemBytesRead))
                {
                    bytesRead += itemBytesRead;
                    return false;
                }
                bytesRead += elementLength;
                result[i] = item;
            }
            value = result;
            return true;
        }
        public static bool TryReadBinaryObjectListLittleEndian<T>(ReadOnlySpan<byte> source, int elementLength, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out List<T>? value, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            value = null;
            bytesRead = 0;
            var numberOfElements = source.Length / elementLength;
            var result = new List<T>(numberOfElements);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadLittleEndian(source.Slice(i * elementLength, elementLength), out var item, out var itemBytesRead))
                {
                    bytesRead += itemBytesRead;
                    return false;
                }
                bytesRead += elementLength;
                result.Add(item);
            }
            value = result;
            return true;
        }
        public static bool TryReadBinaryObjectListBigEndian<T>(ReadOnlySpan<byte> source, int elementLength, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out List<T>? value, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            value = null;
            bytesRead = 0;
            var numberOfElements = source.Length / elementLength;
            var result = new List<T>(numberOfElements);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadBigEndian(source.Slice(i * elementLength, elementLength), out var item, out var itemBytesRead))
                {
                    bytesRead += itemBytesRead;
                    return false;
                }
                bytesRead += elementLength;
                result.Add(item);
            }
            value = result;
            return true;
        }
    }
}
