//HintName: BinaryObjectsGenerator.g.cs
// <auto-generated/>
#nullable enable

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="First"/></term> <description>1</description> </item>
/// <item> <term><see cref="Second"/></term> <description>1</description> </item>
/// <item> <term> --- </term> <description>2</description> </item>
/// </list> </remarks>
[global::Darp.BinaryObjects.BinaryConstant(2)]
public sealed partial record Pair : global::Darp.BinaryObjects.IBinaryObject<Pair>
{
    /// <inheritdoc />
    [global::System.Diagnostics.Contracts.Pure]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => 2;

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 2)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[0..1], this.First);
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[1..2], this.Second);
        bytesWritten += 2;

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 2)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[0..1], this.First);
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[1..2], this.Second);
        bytesWritten += 2;

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Pair? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Pair? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 2)
            return false;
        var ___readFirst = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[0..1]);
        var ___readSecond = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[1..2]);
        bytesRead += 2;

        value = new Pair(___readFirst, ___readSecond);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Pair? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Pair? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 2)
            return false;
        var ___readFirst = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[0..1]);
        var ___readSecond = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[1..2]);
        bytesRead += 2;

        value = new Pair(___readFirst, ___readSecond);
        return true;
    }
}

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Length"/></term> <description>2</description> </item>
/// <item> <term><see cref="Values"/></term> <description><see cref="Length"/></description> </item>
/// <item> <term><see cref="Narrow"/></term> <description><see cref="Length"/></description> </item>
/// <item> <term><see cref="Objects"/></term> <description><see cref="Length"/></description> </item>
/// <item> <term><see cref="Bytes"/></term> <description><see cref="Length"/></description> </item>
/// <item> <term><see cref="Tail"/></term> <description>1</description> </item>
/// <item> <term> --- </term> <description>2 + <see cref="Length"/> + <see cref="Length"/> + <see cref="Length"/> + <see cref="Length"/> + 1</description> </item>
/// </list> </remarks>
public sealed partial record TestObject : global::Darp.BinaryObjects.IBinaryObject<TestObject>
{
    /// <inheritdoc />
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => checked(2 + this.Length + global::System.Math.Max((int)this.Length, 3) + this.Length + this.Length + 1);

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 2)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt16LittleEndian(destination[0..2], this.Length);
        destination = destination[2..];
        bytesWritten += 2;

        if (this.Length < 0 || this.Length > destination.Length || this.Length % 4 != 0 || this.Values.Length < this.Length / 4)
            return false;
        var ___byteLengthValues = this.Length;
        global::Darp.BinaryObjects.Generated.Utilities.WriteInt32SpanLittleEndian(destination[0..___byteLengthValues], this.Values);
        destination = destination[___byteLengthValues..];
        bytesWritten += ___byteLengthValues;

        if (this.Length < 0 || this.Length > destination.Length || this.Length % 3 != 0 || this.Length / 3 < 1 || this.Narrow.Count < this.Length / 3)
            return false;
        var ___byteLengthNarrow = this.Length;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteUInt32SpanLittleEndian(destination[0..___byteLengthNarrow], global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Narrow), 3, out var ___bytesWrittenNarrow))
        {
            bytesWritten += ___bytesWrittenNarrow;
            return false;
        }
        destination = destination[___byteLengthNarrow..];
        bytesWritten += ___byteLengthNarrow;

        if (this.Length < 0 || this.Length > destination.Length || this.Length % 2 != 0 || this.Objects.Length < this.Length / 2)
            return false;
        var ___byteLengthObjects = this.Length;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanLittleEndian<Pair>(destination[0..___byteLengthObjects], this.Objects.Span, 2, out var ___bytesWrittenObjects))
        {
            bytesWritten += ___bytesWrittenObjects;
            return false;
        }
        destination = destination[___byteLengthObjects..];
        bytesWritten += ___byteLengthObjects;

        if (this.Length < 0 || this.Length > destination.Length || this.Bytes.Length < this.Length)
            return false;
        var ___byteLengthBytes = this.Length;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8Span(destination[0..___byteLengthBytes], this.Bytes);
        destination = destination[___byteLengthBytes..];
        bytesWritten += ___byteLengthBytes;

        if (destination.Length < 1)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[0..1], this.Tail);
        bytesWritten += 1;

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 2)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt16BigEndian(destination[0..2], this.Length);
        destination = destination[2..];
        bytesWritten += 2;

        if (this.Length < 0 || this.Length > destination.Length || this.Length % 4 != 0 || this.Values.Length < this.Length / 4)
            return false;
        var ___byteLengthValues = this.Length;
        global::Darp.BinaryObjects.Generated.Utilities.WriteInt32SpanBigEndian(destination[0..___byteLengthValues], this.Values);
        destination = destination[___byteLengthValues..];
        bytesWritten += ___byteLengthValues;

        if (this.Length < 0 || this.Length > destination.Length || this.Length % 3 != 0 || this.Length / 3 < 1 || this.Narrow.Count < this.Length / 3)
            return false;
        var ___byteLengthNarrow = this.Length;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteUInt32SpanBigEndian(destination[0..___byteLengthNarrow], global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Narrow), 3, out var ___bytesWrittenNarrow))
        {
            bytesWritten += ___bytesWrittenNarrow;
            return false;
        }
        destination = destination[___byteLengthNarrow..];
        bytesWritten += ___byteLengthNarrow;

        if (this.Length < 0 || this.Length > destination.Length || this.Length % 2 != 0 || this.Objects.Length < this.Length / 2)
            return false;
        var ___byteLengthObjects = this.Length;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectSpanBigEndian<Pair>(destination[0..___byteLengthObjects], this.Objects.Span, 2, out var ___bytesWrittenObjects))
        {
            bytesWritten += ___bytesWrittenObjects;
            return false;
        }
        destination = destination[___byteLengthObjects..];
        bytesWritten += ___byteLengthObjects;

        if (this.Length < 0 || this.Length > destination.Length || this.Bytes.Length < this.Length)
            return false;
        var ___byteLengthBytes = this.Length;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8Span(destination[0..___byteLengthBytes], this.Bytes);
        destination = destination[___byteLengthBytes..];
        bytesWritten += ___byteLengthBytes;

        if (destination.Length < 1)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[0..1], this.Tail);
        bytesWritten += 1;

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 2)
            return false;
        var ___readLength = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt16LittleEndian(source[0..2]);
        source = source[2..];
        bytesRead += 2;

        if (___readLength < 0 || ___readLength > source.Length || ___readLength % 4 != 0)
            return false;
        var ___byteLengthValues = ___readLength;
        var ___readValues = global::Darp.BinaryObjects.Generated.Utilities.ReadInt32ArrayLittleEndian(source[0..___byteLengthValues], out _);
        source = source[___byteLengthValues..];
        bytesRead += ___byteLengthValues;

        if (___readLength < 0 || ___readLength > source.Length || ___readLength % 3 != 0 || ___readLength / 3 < 1)
            return false;
        var ___byteLengthNarrow = ___readLength;
        var ___readNarrow = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt32ListLittleEndian(source[0..___byteLengthNarrow], 3, out _);
        source = source[___byteLengthNarrow..];
        bytesRead += ___byteLengthNarrow;

        if (___readLength < 0 || ___readLength > source.Length || ___readLength % 2 != 0)
            return false;
        var ___byteLengthObjects = ___readLength;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectArrayLittleEndian<Pair>(source[0..___byteLengthObjects], 2, out var ___readObjects, out var ___bytesReadObjects))
        {
            bytesRead += ___bytesReadObjects;
            return false;
        }
        source = source[___byteLengthObjects..];
        bytesRead += ___byteLengthObjects;

        if (___readLength < 0 || ___readLength > source.Length)
            return false;
        var ___byteLengthBytes = ___readLength;
        var ___readBytes = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8Array(source[0..___byteLengthBytes], out _);
        source = source[___byteLengthBytes..];
        bytesRead += ___byteLengthBytes;

        if (source.Length < 1)
            return false;
        var ___readTail = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[0..1]);
        bytesRead += 1;

        value = new TestObject(___readLength, ___readValues, ___readNarrow, ___readObjects, ___readBytes, ___readTail);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 2)
            return false;
        var ___readLength = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt16BigEndian(source[0..2]);
        source = source[2..];
        bytesRead += 2;

        if (___readLength < 0 || ___readLength > source.Length || ___readLength % 4 != 0)
            return false;
        var ___byteLengthValues = ___readLength;
        var ___readValues = global::Darp.BinaryObjects.Generated.Utilities.ReadInt32ArrayBigEndian(source[0..___byteLengthValues], out _);
        source = source[___byteLengthValues..];
        bytesRead += ___byteLengthValues;

        if (___readLength < 0 || ___readLength > source.Length || ___readLength % 3 != 0 || ___readLength / 3 < 1)
            return false;
        var ___byteLengthNarrow = ___readLength;
        var ___readNarrow = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt32ListBigEndian(source[0..___byteLengthNarrow], 3, out _);
        source = source[___byteLengthNarrow..];
        bytesRead += ___byteLengthNarrow;

        if (___readLength < 0 || ___readLength > source.Length || ___readLength % 2 != 0)
            return false;
        var ___byteLengthObjects = ___readLength;
        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectArrayBigEndian<Pair>(source[0..___byteLengthObjects], 2, out var ___readObjects, out var ___bytesReadObjects))
        {
            bytesRead += ___bytesReadObjects;
            return false;
        }
        source = source[___byteLengthObjects..];
        bytesRead += ___byteLengthObjects;

        if (___readLength < 0 || ___readLength > source.Length)
            return false;
        var ___byteLengthBytes = ___readLength;
        var ___readBytes = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8Array(source[0..___byteLengthBytes], out _);
        source = source[___byteLengthBytes..];
        bytesRead += ___byteLengthBytes;

        if (source.Length < 1)
            return false;
        var ___readTail = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[0..1]);
        bytesRead += 1;

        value = new TestObject(___readLength, ___readValues, ___readNarrow, ___readObjects, ___readBytes, ___readTail);
        return true;
    }
}

namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    [GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    file static class Utilities
    {
        /// <summary> Writes a <c>byte</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt8(Span<byte> destination, byte value)
        {
            destination[0] = value;
        }
        /// <summary> Reads a <c>byte</c> from the given source </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte ReadUInt8(ReadOnlySpan<byte> source)
        {
            return source[0];
        }
        /// <summary> Writes a <c>ReadOnlySpan&lt;byte&gt;</c> with a <c>maxElementLength</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt8Span(Span<byte> destination, ReadOnlySpan<byte> value)
        {
            var length = Math.Min(value.Length, destination.Length);
            value.Slice(0, length).CopyTo(destination);
            return length;
        }
        /// <summary> Reads a <c>byte[]</c> from the given source </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte[] ReadUInt8Array(ReadOnlySpan<byte> source, out int bytesRead)
        {
            bytesRead = source.Length;
            return source.ToArray();
        }
        /// <summary> Writes a <c>ushort</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt16LittleEndian(Span<byte> destination, ushort value)
        {
            BinaryPrimitives.WriteUInt16LittleEndian(destination, value);
        }
        /// <summary> Writes a <c>ushort</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt16BigEndian(Span<byte> destination, ushort value)
        {
            BinaryPrimitives.WriteUInt16BigEndian(destination, value);
        }
        /// <summary> Reads a <c>ushort</c> from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort ReadUInt16LittleEndian(ReadOnlySpan<byte> source)
        {
            return BinaryPrimitives.ReadUInt16LittleEndian(source);
        }
        /// <summary> Reads a <c>ushort</c> from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort ReadUInt16BigEndian(ReadOnlySpan<byte> source)
        {
            return BinaryPrimitives.ReadUInt16BigEndian(source);
        }
        /// <summary> Writes the elements of a <c>ReadOnlySpan&lt;uint&gt;</c> with <c>elementLength</c> bytes each to the destination, as LittleEndian. Fails at the first element which does not fit </summary>
        public static bool TryWriteUInt32SpanLittleEndian(Span<byte> destination, ReadOnlySpan<uint> value, int elementLength, out int bytesWritten)
        {
            bytesWritten = 0;
            var numberOfElements = Math.Min(value.Length, destination.Length / elementLength);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!FitsUnsigned(value[i], elementLength))
                    return false;
                WriteUnsignedLittleEndian(destination.Slice(bytesWritten, elementLength), value[i]);
                bytesWritten += elementLength;
            }
            return true;
        }
        /// <summary> Writes the elements of a <c>ReadOnlySpan&lt;uint&gt;</c> with <c>elementLength</c> bytes each to the destination, as BigEndian. Fails at the first element which does not fit </summary>
        public static bool TryWriteUInt32SpanBigEndian(Span<byte> destination, ReadOnlySpan<uint> value, int elementLength, out int bytesWritten)
        {
            bytesWritten = 0;
            var numberOfElements = Math.Min(value.Length, destination.Length / elementLength);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!FitsUnsigned(value[i], elementLength))
                    return false;
                WriteUnsignedBigEndian(destination.Slice(bytesWritten, elementLength), value[i]);
                bytesWritten += elementLength;
            }
            return true;
        }
        /// <summary> Reads a <c>List&lt;uint&gt;</c> with <c>elementLength</c> bytes per element from the given source, as LittleEndian </summary>
        public static List<uint> ReadUInt32ListLittleEndian(ReadOnlySpan<byte> source, int elementLength, out int bytesRead)
        {
            var result = new List<uint>();
            CollectionsMarshal.SetCount(result, source.Length / elementLength);
            Span<uint> integers = CollectionsMarshal.AsSpan(result);
            for (var i = 0; i < integers.Length; i++)
                integers[i] = (uint)ReadUnsignedLittleEndian(source.Slice(i * elementLength, elementLength));
            bytesRead = integers.Length * elementLength;
            return result;
        }
        /// <summary> Reads a <c>List&lt;uint&gt;</c> with <c>elementLength</c> bytes per element from the given source, as BigEndian </summary>
        public static List<uint> ReadUInt32ListBigEndian(ReadOnlySpan<byte> source, int elementLength, out int bytesRead)
        {
            var result = new List<uint>();
            CollectionsMarshal.SetCount(result, source.Length / elementLength);
            Span<uint> integers = CollectionsMarshal.AsSpan(result);
            for (var i = 0; i < integers.Length; i++)
                integers[i] = (uint)ReadUnsignedBigEndian(source.Slice(i * elementLength, elementLength));
            bytesRead = integers.Length * elementLength;
            return result;
        }
        /// <summary> Writes a <c>ReadOnlySpan&lt;int&gt;</c> with a <c>maxElementLength</c> to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteInt32SpanLittleEndian(Span<byte> destination, ReadOnlySpan<int> value)
        {
            var length = Math.Min(value.Length, destination.Length / 4);
            if (!BitConverter.IsLittleEndian)
            {
                Span<int> reinterpretedDestination = MemoryMarshal.Cast<byte, int>(destination);
                BinaryPrimitives.ReverseEndianness(value[..length], reinterpretedDestination);
                return length * 4;
            }
            MemoryMarshal.Cast<int, byte>(value[..length]).CopyTo(destination);
            return length * 4;
        }
        /// <summary> Writes a <c>ReadOnlySpan&lt;int&gt;</c> with a <c>maxElementLength</c> to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteInt32SpanBigEndian(Span<byte> destination, ReadOnlySpan<int> value)
        {
            var length = Math.Min(value.Length, destination.Length / 4);
            if (BitConverter.IsLittleEndian)
            {
                Span<int> reinterpretedDestination = MemoryMarshal.Cast<byte, int>(destination);
                BinaryPrimitives.ReverseEndianness(value[..length], reinterpretedDestination);
                return length * 4;
            }
            MemoryMarshal.Cast<int, byte>(value[..length]).CopyTo(destination);
            return length * 4;
        }
        /// <summary> Reads a <c>int[]</c> from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int[] ReadInt32ArrayLittleEndian(ReadOnlySpan<byte> source, out int bytesRead)
        {
            var array = MemoryMarshal.Cast<byte, int>(source).ToArray();
            if (!BitConverter.IsLittleEndian)
                BinaryPrimitives.ReverseEndianness(array, array);
            bytesRead = array.Length * 4;
            return array;
        }
        /// <summary> Reads a <c>int[]</c> from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int[] ReadInt32ArrayBigEndian(ReadOnlySpan<byte> source, out int bytesRead)
        {
            var array = MemoryMarshal.Cast<byte, int>(source).ToArray();
            if (BitConverter.IsLittleEndian)
                BinaryPrimitives.ReverseEndianness(array, array);
            bytesRead = array.Length * 4;
            return array;
        }
        /// <summary> Checks whether an unsigned integer can be written with <c>byteCount</c> bytes </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool FitsUnsigned(ulong value, int byteCount)
        {
            return (value >> (8 * byteCount)) == 0;
        }
        /// <summary> Writes the lowest <c>destination.Length</c> bytes of an unsigned integer to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUnsignedLittleEndian(Span<byte> destination, ulong value)
        {
            for (var i = 0; i < destination.Length; i++)
            {
                destination[i] = unchecked((byte)value);
                value >>= 8;
            }
        }
        /// <summary> Writes the lowest <c>destination.Length</c> bytes of an unsigned integer to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUnsignedBigEndian(Span<byte> destination, ulong value)
        {
            for (var i = destination.Length - 1; i >= 0; i--)
            {
                destination[i] = unchecked((byte)value);
                value >>= 8;
            }
        }
        /// <summary> Reads an unsigned integer of <c>source.Length</c> bytes from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong ReadUnsignedLittleEndian(ReadOnlySpan<byte> source)
        {
            ulong value = source[^1];
            for (var i = source.Length - 2; i >= 0; i--)
                value = (value << 8) | source[i];
            return value;
        }
        /// <summary> Reads an unsigned integer of <c>source.Length</c> bytes from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong ReadUnsignedBigEndian(ReadOnlySpan<byte> source)
        {
            ulong value = source[0];
            for (var i = 1; i < source.Length; i++)
                value = (value << 8) | source[i];
            return value;
        }
        public static bool TryWriteBinaryObjectSpanLittleEndian<T>(Span<byte> destination, ReadOnlySpan<T> value, int elementLength, out int bytesWritten)
            where T : IBinaryWritable
        {
            bytesWritten = 0;
            var numberOfElements = Math.Min(value.Length, destination.Length / elementLength);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!value[i].TryWriteLittleEndian(destination.Slice(i * elementLength, elementLength), out var itemBytesWritten))
                {
                    bytesWritten += itemBytesWritten;
                    return false;
                }
                bytesWritten += elementLength;
            }
            return true;
        }
        public static bool TryWriteBinaryObjectSpanBigEndian<T>(Span<byte> destination, ReadOnlySpan<T> value, int elementLength, out int bytesWritten)
            where T : IBinaryWritable
        {
            bytesWritten = 0;
            var numberOfElements = Math.Min(value.Length, destination.Length / elementLength);
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!value[i].TryWriteBigEndian(destination.Slice(i * elementLength, elementLength), out var itemBytesWritten))
                {
                    bytesWritten += itemBytesWritten;
                    return false;
                }
                bytesWritten += elementLength;
            }
            return true;
        }
        public static bool TryReadBinaryObjectArrayLittleEndian<T>(ReadOnlySpan<byte> source, int elementLength, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T[]? value, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            value = null;
            bytesRead = 0;
            var numberOfElements = source.Length / elementLength;
            var result = new T[numberOfElements];
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadLittleEndian(source.Slice(i * elementLength, elementLength), out var item, out var itemBytesRead))
                {
                    bytesRead += itemBytesRead;
                    return false;
                }
                bytesRead += elementLength;
                result[i] = item;
            }
            value = result;
            return true;
        }
        public static bool TryReadBinaryObjectArrayBigEndian<T>(ReadOnlySpan<byte> source, int elementLength, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T[]? value, out int bytesRead)
            where T : IBinaryReadable<T>
        {
            value = null;
            bytesRead = 0;
            var numberOfElements = source.Length / elementLength;
            var result = new T[numberOfElements];
            for (var i = 0; i < numberOfElements; i++)
            {
                if (!T.TryReadBigEndian(source.Slice(i * elementLength, elementLength), out var item, out var itemBytesRead))
                {
                    bytesRead += itemBytesRead;
                    return false;
                }
                bytesRead += elementLength;
                result[i] = item;
            }
            value = result;
            return true;
        }
    }
}
