//HintName: BinaryObjectsGenerator.g.cs
// <auto-generated/>
#nullable enable

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Value"/></term> <description><see cref="global::Darp.BinaryObjects.IBinaryWritable.GetByteCount()"/></description> </item>
/// <item> <term><see cref="Tail"/></term> <description>1</description> </item>
/// <item> <term> --- </term> <description><see cref="global::Darp.BinaryObjects.IBinaryWritable.GetByteCount()"/> + 1</description> </item>
/// </list> </remarks>
public sealed partial record Parent : global::Darp.BinaryObjects.IBinaryObject<Parent>
{
    /// <inheritdoc />
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => checked(global::Darp.BinaryObjects.Generated.Utilities.GetBinaryObjectByteCount(this.Value) + 1);

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectLittleEndian(destination[0..], this.Value, out var ___bytesWrittenValue))
            return false;
        destination = destination[___bytesWrittenValue..];
        destination = destination[0..];
        bytesWritten += ___bytesWrittenValue;

        if (destination.Length < 1)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[0..1], this.Tail);
        bytesWritten += 1;

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (!global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObjectBigEndian(destination[0..], this.Value, out var ___bytesWrittenValue))
            return false;
        destination = destination[___bytesWrittenValue..];
        destination = destination[0..];
        bytesWritten += ___bytesWrittenValue;

        if (destination.Length < 1)
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt8(destination[0..1], this.Tail);
        bytesWritten += 1;

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectLittleEndian<ManualObject>(source[0..], out var ___readValue, out var ___bytesReadValue))
            return false;
        source = source[___bytesReadValue..];
        bytesRead += ___bytesReadValue;

        if (source.Length < 1)
            return false;
        var ___readTail = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[0..1]);
        bytesRead += 1;

        value = new Parent(___readValue, ___readTail);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Parent? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (!global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObjectBigEndian<ManualObject>(source[0..], out var ___readValue, out var ___bytesReadValue))
            return false;
        source = source[___bytesReadValue..];
        bytesRead += ___bytesReadValue;

        if (source.Length < 1)
            return false;
        var ___readTail = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt8(source[0..1]);
        bytesRead += 1;

        value = new Parent(___readValue, ___readTail);
        return true;
    }
}

namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    [GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    file static class Utilities
    {
        /// <summary> Writes a <c>byte</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt8(Span<byte> destination, byte value)
        {
            destination[0] = value;
        }
        /// <summary> Reads a <c>byte</c> from the given source </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte ReadUInt8(ReadOnlySpan<byte> source)
        {
            return source[0];
        }
        public static int GetBinaryObjectByteCount<T>(T value)
            where T : IBinaryWritable => value.GetByteCount();
        public static bool TryWriteBinaryObjectLittleEndian<T>(Span<byte> destination, T value, out int bytesWritten)
            where T : IBinaryWritable => value.TryWriteLittleEndian(destination, out bytesWritten);
        public static bool TryWriteBinaryObjectBigEndian<T>(Span<byte> destination, T value, out int bytesWritten)
            where T : IBinaryWritable => value.TryWriteBigEndian(destination, out bytesWritten);
        public static bool TryReadBinaryObjectLittleEndian<T>(ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? value, out int bytesRead)
            where T : IBinaryReadable<T> => T.TryReadLittleEndian(source, out value, out bytesRead);
        public static bool TryReadBinaryObjectBigEndian<T>(ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? value, out int bytesRead)
            where T : IBinaryReadable<T> => T.TryReadBigEndian(source, out value, out bytesRead);
    }
}
