<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <BinaryObjectsGenerator_IsUtilityClassInternal>true</BinaryObjectsGenerator_IsUtilityClassInternal>
    <!-- Generated code has to work in projects which check arithmetic overflow -->
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Darp.BinaryObjects\Darp.BinaryObjects.csproj" />
    <ProjectReference
      Include="..\..\src\Darp.BinaryObjects.Generator\Darp.BinaryObjects.Generator.csproj"
      OutputItemType="Analyzer"
    />
  </ItemGroup>

  <Import Project="..\..\src\Darp.BinaryObjects.Generator\buildTransitive\Darp.BinaryObjects.Generator.props" />
</Project>
