//HintName: BinaryObjectsGenerator.g.cs
// <auto-generated/>
#nullable enable

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Values"/></term> <description>2 * n</description> </item>
/// <item> <term> --- </term> <description>2 * n</description> </item>
/// </list> </remarks>
public sealed partial record TestObject : global::Darp.BinaryObjects.IBinaryObject<TestObject>
{
    /// <inheritdoc />
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => checked(2 * global::System.Linq.Enumerable.Count(this.Values));

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (global::System.Linq.Enumerable.Count(this.Values) > destination.Length / 2)
            return false;
        bytesWritten += global::Darp.BinaryObjects.Generated.Utilities.WriteUInt16EnumEnumerableLittleEndian<Status>(destination, this.Values);

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (global::System.Linq.Enumerable.Count(this.Values) > destination.Length / 2)
            return false;
        bytesWritten += global::Darp.BinaryObjects.Generated.Utilities.WriteUInt16EnumEnumerableBigEndian<Status>(destination, this.Values);

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        var ___readValues = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt16EnumArrayLittleEndian<Status>(source, out int ___bytesReadValues);
        bytesRead += ___bytesReadValues;

        value = new TestObject(___readValues);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        var ___readValues = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt16EnumArrayBigEndian<Status>(source, out int ___bytesReadValues);
        bytesRead += ___bytesReadValues;

        value = new TestObject(___readValues);
        return true;
    }
}

namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    [GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    file static class Utilities
    {
        /// <summary> Writes a <c>ReadOnlySpan&lt;TEnum&gt;</c> with a <c>maxElementLength</c> to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt16EnumSpanLittleEndian<TEnum>(Span<byte> destination, ReadOnlySpan<TEnum> value)
            where TEnum : unmanaged, Enum
        {
            var length = Math.Min(value.Length, destination.Length / 2);
            if (!BitConverter.IsLittleEndian)
            {
                ReadOnlySpan<ushort> reinterpretedValue = MemoryMarshal.Cast<TEnum, ushort>(value);
                Span<ushort> reinterpretedDestination = MemoryMarshal.Cast<byte, ushort>(destination);
                BinaryPrimitives.ReverseEndianness(reinterpretedValue[..length], reinterpretedDestination);
                return length * 2;
            }
            MemoryMarshal.Cast<TEnum, byte>(value[..length]).CopyTo(destination);
            return length * 2;
        }
        /// <summary> Writes a <c>ReadOnlySpan&lt;TEnum&gt;</c> with a <c>maxElementLength</c> to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt16EnumSpanBigEndian<TEnum>(Span<byte> destination, ReadOnlySpan<TEnum> value)
            where TEnum : unmanaged, Enum
        {
            var length = Math.Min(value.Length, destination.Length / 2);
            if (BitConverter.IsLittleEndian)
            {
                ReadOnlySpan<ushort> reinterpretedValue = MemoryMarshal.Cast<TEnum, ushort>(value);
                Span<ushort> reinterpretedDestination = MemoryMarshal.Cast<byte, ushort>(destination);
                BinaryPrimitives.ReverseEndianness(reinterpretedValue[..length], reinterpretedDestination);
                return length * 2;
            }
            MemoryMarshal.Cast<TEnum, byte>(value[..length]).CopyTo(destination);
            return length * 2;
        }
        /// <summary> Reads a <c>TEnum[]</c> from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TEnum[] ReadUInt16EnumArrayLittleEndian<TEnum>(ReadOnlySpan<byte> source, out int bytesRead)
            where TEnum : unmanaged, Enum
        {
            var array = MemoryMarshal.Cast<byte, TEnum>(source).ToArray();
            if (!BitConverter.IsLittleEndian)
            {
                Span<ushort> reinterpretedArray = MemoryMarshal.Cast<TEnum, ushort>(array.AsSpan());
                BinaryPrimitives.ReverseEndianness(reinterpretedArray, reinterpretedArray);
            }
            bytesRead = array.Length * 2;
            return array;
        }
        /// <summary> Reads a <c>TEnum[]</c> from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TEnum[] ReadUInt16EnumArrayBigEndian<TEnum>(ReadOnlySpan<byte> source, out int bytesRead)
            where TEnum : unmanaged, Enum
        {
            var array = MemoryMarshal.Cast<byte, TEnum>(source).ToArray();
            if (BitConverter.IsLittleEndian)
            {
                Span<ushort> reinterpretedArray = MemoryMarshal.Cast<TEnum, ushort>(array.AsSpan());
                BinaryPrimitives.ReverseEndianness(reinterpretedArray, reinterpretedArray);
            }
            bytesRead = array.Length * 2;
            return array;
        }
        /// <summary> Writes a <c>List&lt;TEnum&gt;</c> with a <c>maxElementLength</c> to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt16EnumListLittleEndian<TEnum>(Span<byte> destination, List<TEnum> value)
            where TEnum : unmanaged, Enum
        {
            return WriteUInt16EnumSpanLittleEndian<TEnum>(destination, CollectionsMarshal.AsSpan(value));
        }
        /// <summary> Writes a <c>List&lt;TEnum&gt;</c> with a <c>maxElementLength</c> to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt16EnumListBigEndian<TEnum>(Span<byte> destination, List<TEnum> value)
            where TEnum : unmanaged, Enum
        {
            return WriteUInt16EnumSpanBigEndian<TEnum>(destination, CollectionsMarshal.AsSpan(value));
        }
        /// <summary> Writes a <c>IEnumerable&lt;TEnum&gt;</c> with a <c>maxElementLength</c> to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt16EnumEnumerableLittleEndian<TEnum>(Span<byte> destination, IEnumerable<TEnum> value)
            where TEnum : unmanaged, Enum
        {
            switch (value)
            {
                case TEnum[] arrayValue:
                    return WriteUInt16EnumSpanLittleEndian<TEnum>(destination, arrayValue);
                case List<TEnum> listValue:
                    return WriteUInt16EnumListLittleEndian<TEnum>(destination, listValue);
            }
            var maxElementLength = destination.Length / 2;
            var index = 0;
            foreach (var val in value)
            {
                if (index >= maxElementLength)
                    break;
                var item = val;
                ReadOnlySpan<TEnum> element = MemoryMarshal.CreateReadOnlySpan(ref item, 1);
                WriteUInt16EnumSpanLittleEndian<TEnum>(destination.Slice(index * 2, 2), element);
                index++;
            }
            return index * 2;
        }
        /// <summary> Writes a <c>IEnumerable&lt;TEnum&gt;</c> with a <c>maxElementLength</c> to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int WriteUInt16EnumEnumerableBigEndian<TEnum>(Span<byte> destination, IEnumerable<TEnum> value)
            where TEnum : unmanaged, Enum
        {
            switch (value)
            {
                case TEnum[] arrayValue:
                    return WriteUInt16EnumSpanBigEndian<TEnum>(destination, arrayValue);
                case List<TEnum> listValue:
                    return WriteUInt16EnumListBigEndian<TEnum>(destination, listValue);
            }
            var maxElementLength = destination.Length / 2;
            var index = 0;
            foreach (var val in value)
            {
                if (index >= maxElementLength)
                    break;
                var item = val;
                ReadOnlySpan<TEnum> element = MemoryMarshal.CreateReadOnlySpan(ref item, 1);
                WriteUInt16EnumSpanBigEndian<TEnum>(destination.Slice(index * 2, 2), element);
                index++;
            }
            return index * 2;
        }
    }
}
