//HintName: BinaryObjectsGenerator.g.cs
// <auto-generated/>
#nullable enable

/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
/// <item> <term><see cref="Unsigned"/></term> <description>3</description> </item>
/// <item> <term><see cref="Signed"/></term> <description>6</description> </item>
/// <item> <term><see cref="Unchanged"/></term> <description>2</description> </item>
/// <item> <term><see cref="UnsignedEnum"/></term> <description>3</description> </item>
/// <item> <term><see cref="SignedEnum"/></term> <description>1</description> </item>
/// <item> <term> --- </term> <description>15</description> </item>
/// </list> </remarks>
[global::Darp.BinaryObjects.BinaryConstant(15)]
public sealed partial record TestObject : global::Darp.BinaryObjects.IBinaryObject<TestObject>
{
    /// <inheritdoc />
    [global::System.Diagnostics.Contracts.Pure]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public int GetByteCount() => 15;

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination) => TryWriteLittleEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteLittleEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 15 || !global::Darp.BinaryObjects.Generated.Utilities.FitsUnsigned(this.Unsigned, 3) || !global::Darp.BinaryObjects.Generated.Utilities.FitsSigned(this.Signed, 6) || !global::Darp.BinaryObjects.Generated.Utilities.FitsUnsigned((uint) this.UnsignedEnum, 3) || !global::Darp.BinaryObjects.Generated.Utilities.FitsSigned((short) this.SignedEnum, 1))
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUnsignedLittleEndian(destination[0..3], this.Unsigned);
        global::Darp.BinaryObjects.Generated.Utilities.WriteSignedLittleEndian(destination[3..9], this.Signed);
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt16LittleEndian(destination[9..11], this.Unchanged);
        global::Darp.BinaryObjects.Generated.Utilities.WriteUnsignedLittleEndian(destination[11..14], (uint) this.UnsignedEnum);
        global::Darp.BinaryObjects.Generated.Utilities.WriteSignedLittleEndian(destination[14..15], (short) this.SignedEnum);
        bytesWritten += 15;

        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination) => TryWriteBigEndian(destination, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public bool TryWriteBigEndian(global::System.Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;

        if (destination.Length < 15 || !global::Darp.BinaryObjects.Generated.Utilities.FitsUnsigned(this.Unsigned, 3) || !global::Darp.BinaryObjects.Generated.Utilities.FitsSigned(this.Signed, 6) || !global::Darp.BinaryObjects.Generated.Utilities.FitsUnsigned((uint) this.UnsignedEnum, 3) || !global::Darp.BinaryObjects.Generated.Utilities.FitsSigned((short) this.SignedEnum, 1))
            return false;
        global::Darp.BinaryObjects.Generated.Utilities.WriteUnsignedBigEndian(destination[0..3], this.Unsigned);
        global::Darp.BinaryObjects.Generated.Utilities.WriteSignedBigEndian(destination[3..9], this.Signed);
        global::Darp.BinaryObjects.Generated.Utilities.WriteUInt16BigEndian(destination[9..11], this.Unchanged);
        global::Darp.BinaryObjects.Generated.Utilities.WriteUnsignedBigEndian(destination[11..14], (uint) this.UnsignedEnum);
        global::Darp.BinaryObjects.Generated.Utilities.WriteSignedBigEndian(destination[14..15], (short) this.SignedEnum);
        bytesWritten += 15;

        return true;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadLittleEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadLittleEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 15)
            return false;
        var ___readUnsigned = (uint) global::Darp.BinaryObjects.Generated.Utilities.ReadUnsignedLittleEndian(source[0..3]);
        var ___readSigned = global::Darp.BinaryObjects.Generated.Utilities.ReadSignedLittleEndian(source[3..9]);
        var ___readUnchanged = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt16LittleEndian(source[9..11]);
        var ___readUnsignedEnum = (UIntEnum) global::Darp.BinaryObjects.Generated.Utilities.ReadUnsignedLittleEndian(source[11..14]);
        var ___readSignedEnum = (ShortEnum) global::Darp.BinaryObjects.Generated.Utilities.ReadSignedLittleEndian(source[14..15]);
        bytesRead += 15;

        value = new TestObject(___readUnsigned, ___readSigned, ___readUnchanged, ___readUnsignedEnum, ___readSignedEnum);
        return true;
    }
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value) => TryReadBigEndian(source, out value, out _);
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    public static bool TryReadBigEndian(global::System.ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestObject? value, out int bytesRead)
    {
        bytesRead = 0;
        value = default;

        if (source.Length < 15)
            return false;
        var ___readUnsigned = (uint) global::Darp.BinaryObjects.Generated.Utilities.ReadUnsignedBigEndian(source[0..3]);
        var ___readSigned = global::Darp.BinaryObjects.Generated.Utilities.ReadSignedBigEndian(source[3..9]);
        var ___readUnchanged = global::Darp.BinaryObjects.Generated.Utilities.ReadUInt16BigEndian(source[9..11]);
        var ___readUnsignedEnum = (UIntEnum) global::Darp.BinaryObjects.Generated.Utilities.ReadUnsignedBigEndian(source[11..14]);
        var ___readSignedEnum = (ShortEnum) global::Darp.BinaryObjects.Generated.Utilities.ReadSignedBigEndian(source[14..15]);
        bytesRead += 15;

        value = new TestObject(___readUnsigned, ___readSigned, ___readUnchanged, ___readUnsignedEnum, ___readSignedEnum);
        return true;
    }
}

namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    [GeneratedCodeAttribute("Darp.BinaryObjects.Generator", "GeneratorVersion")]
    file static class Utilities
    {
        /// <summary> Writes a <c>ushort</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt16LittleEndian(Span<byte> destination, ushort value)
        {
            BinaryPrimitives.WriteUInt16LittleEndian(destination, value);
        }
        /// <summary> Writes a <c>ushort</c> to the destination </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt16BigEndian(Span<byte> destination, ushort value)
        {
            BinaryPrimitives.WriteUInt16BigEndian(destination, value);
        }
        /// <summary> Reads a <c>ushort</c> from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort ReadUInt16LittleEndian(ReadOnlySpan<byte> source)
        {
            return BinaryPrimitives.ReadUInt16LittleEndian(source);
        }
        /// <summary> Reads a <c>ushort</c> from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort ReadUInt16BigEndian(ReadOnlySpan<byte> source)
        {
            return BinaryPrimitives.ReadUInt16BigEndian(source);
        }
        /// <summary> Checks whether an unsigned integer can be written with <c>byteCount</c> bytes </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool FitsUnsigned(ulong value, int byteCount)
        {
            return (value >> (8 * byteCount)) == 0;
        }
        /// <summary> Writes the lowest <c>destination.Length</c> bytes of an unsigned integer to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUnsignedLittleEndian(Span<byte> destination, ulong value)
        {
            for (var i = 0; i < destination.Length; i++)
            {
                destination[i] = unchecked((byte)value);
                value >>= 8;
            }
        }
        /// <summary> Writes the lowest <c>destination.Length</c> bytes of an unsigned integer to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUnsignedBigEndian(Span<byte> destination, ulong value)
        {
            for (var i = destination.Length - 1; i >= 0; i--)
            {
                destination[i] = unchecked((byte)value);
                value >>= 8;
            }
        }
        /// <summary> Reads an unsigned integer of <c>source.Length</c> bytes from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong ReadUnsignedLittleEndian(ReadOnlySpan<byte> source)
        {
            ulong value = source[^1];
            for (var i = source.Length - 2; i >= 0; i--)
                value = (value << 8) | source[i];
            return value;
        }
        /// <summary> Reads an unsigned integer of <c>source.Length</c> bytes from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong ReadUnsignedBigEndian(ReadOnlySpan<byte> source)
        {
            ulong value = source[0];
            for (var i = 1; i < source.Length; i++)
                value = (value << 8) | source[i];
            return value;
        }
        /// <summary> Checks whether a signed integer can be written with <c>byteCount</c> bytes </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool FitsSigned(long value, int byteCount)
        {
            var shift = 64 - 8 * byteCount;
            return ((value << shift) >> shift) == value;
        }
        /// <summary> Writes the lowest <c>destination.Length</c> bytes of a signed integer to the destination, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteSignedLittleEndian(Span<byte> destination, long value)
        {
            for (var i = 0; i < destination.Length; i++)
            {
                destination[i] = unchecked((byte)value);
                value >>= 8;
            }
        }
        /// <summary> Writes the lowest <c>destination.Length</c> bytes of a signed integer to the destination, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteSignedBigEndian(Span<byte> destination, long value)
        {
            for (var i = destination.Length - 1; i >= 0; i--)
            {
                destination[i] = unchecked((byte)value);
                value >>= 8;
            }
        }
        /// <summary> Reads a signed integer of <c>source.Length</c> bytes from the given source, as LittleEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long ReadSignedLittleEndian(ReadOnlySpan<byte> source)
        {
            long value = unchecked((sbyte)source[^1]);
            for (var i = source.Length - 2; i >= 0; i--)
                value = (value << 8) | source[i];
            return value;
        }
        /// <summary> Reads a signed integer of <c>source.Length</c> bytes from the given source, as BigEndian </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long ReadSignedBigEndian(ReadOnlySpan<byte> source)
        {
            long value = unchecked((sbyte)source[0]);
            for (var i = 1; i < source.Length; i++)
                value = (value << 8) | source[i];
            return value;
        }
    }
}
