namespace Darp.BinaryObjects.Generator;

using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal readonly record struct Aaa2(
    ImmutableArray<DiagnosticData> Diagnostics,
    string? Code,
    ImmutableArray<UtilityData> Utilities
)
{
    public static Aaa2 Fail(IEnumerable<DiagnosticData> diagnostics)
    {
        return new Aaa2(diagnostics.ToImmutableArray(), null, ImmutableArray<UtilityData>.Empty);
    }
}

partial class BinaryObjectsGenerator
{
    public const string Prefix = "___";

    private static bool TryEmit(
        TargetTypeInfo info,
        ImmutableArray<IGroup> memberGroups,
        ImmutableArray<IMember> constructorParameters,
        out Aaa2 aaa2
    )
    {
        var sw = new StringWriter();
        using var writer = new IndentedTextWriter(sw);
        var diagnostics = new List<DiagnosticData>();
        var utilities = new List<UtilityData>();

        EmitOptionalNamespaceStart(writer, info.Symbol);
        EmitAddTypeDeclaration(writer, info, memberGroups);
        writer.WriteLine("{");
        writer.Indent++;
        if (info.GenerateWrite)
        {
            EmitGetByteCountMethod(writer, info.Symbol, memberGroups);
            writer.WriteEmptyLine();
            EmitWriteImplementationMethod(writer, memberGroups, true, utilities);
            EmitWriteImplementationMethod(writer, memberGroups, false, utilities);
            writer.WriteEmptyLine();
        }
        if (info.GenerateRead)
        {
            EmitReadImplementationMethod(writer, info.Symbol, memberGroups, constructorParameters, true, utilities);
            EmitReadImplementationMethod(writer, info.Symbol, memberGroups, constructorParameters, false, utilities);
        }
        writer.Indent--;
        writer.WriteLine("}");
        EmitOptionalNamespaceEnd(writer, info.Symbol);

        aaa2 = new Aaa2(diagnostics.ToImmutableArray(), sw.ToString(), ImmutableArray<UtilityData>.Empty);
        return true;
    }

    private static void EmitFileHeader(IndentedTextWriter writer)
    {
        writer.WriteMultiLine(
            """
// <auto-generated/>
#nullable enable

"""
        );
    }

    private static void EmitOptionalNamespaceStart(IndentedTextWriter writer, INamedTypeSymbol symbol)
    {
        var typeNamespace = symbol.GetNamespace();
        if (string.IsNullOrWhiteSpace(typeNamespace))
            return;
        writer.WriteLine($"namespace {typeNamespace}");
        writer.WriteLine("{");
        writer.Indent++;
    }

    private static void EmitAddTypeDeclaration(
        IndentedTextWriter writer,
        TargetTypeInfo info,
        ImmutableArray<IGroup> memberGroups
    )
    {
        TypeDeclarationSyntax syntax = info.Syntax;
        // Add xml docs
        var memberDocs = memberGroups
            .SelectMembers()
            .Select(memberInfo =>
            {
                var length =
                    memberInfo is BinaryObjectMemberGroup && !info.GenerateWrite
                        ? "variable"
                        : memberInfo.GetDocCommentLength();
                return $"""/// <item> <term><see cref="{memberInfo.MemberSymbol.Name}"/></term> <description>{length}</description> </item>""";
            })
            .ToArray();
        //var summedConstantLength = memberGroups.Sum(x => x.ConstantByteLength);
        var summedLength = memberGroups.Length switch
        {
            > 0 => string.Join(
                " + ",
                memberGroups.Select(x =>
                    x is BinaryObjectMemberGroup && !info.GenerateWrite
                        ? "variable"
                        : x.GetVariableDocCommentLength() ?? $"{x.ConstantByteLength}"
                )
            ),
            _ => "0",
        };
        writer.WriteMultiLine(
            """
/// <remarks> <list type="table">
/// <item> <term><b>Field</b></term> <description><b>Byte Length</b></description> </item>
"""
        );
        if (memberDocs.Length > 0)
            writer.WriteMultiLine(string.Join("\n", memberDocs));
        writer.WriteMultiLine(
            $"""
/// <item> <term> --- </term> <description>{summedLength}</description> </item>
/// </list> </remarks>
"""
        );
        // Add actual type. declaration
        var recordClassOrStruct =
            syntax is RecordDeclarationSyntax recordSyntax
            && !string.IsNullOrWhiteSpace(recordSyntax.ClassOrStructKeyword.Text)
                ? $" {recordSyntax.ClassOrStructKeyword}"
                : "";

        var isPure = memberGroups.SelectMembers().All(x => x is IConstantMember);
        if (isPure)
        {
            var constantLength = memberGroups.Sum(x => x.ConstantByteLength);
            writer.WriteLine($"[global::Darp.BinaryObjects.BinaryConstant({constantLength})]");
        }
        var interfaceName = (info.GenerateRead, info.GenerateWrite) switch
        {
            (true, true) => $"IBinaryObject<{syntax.Identifier}>",
            (true, false) => $"IBinaryReadable<{syntax.Identifier}>",
            _ => "IBinaryWritable",
        };
        writer.WriteLine(
            $"{syntax.Modifiers} {syntax.Keyword}{recordClassOrStruct} {syntax.Identifier} : global::Darp.BinaryObjects.{interfaceName}"
        );
    }

    private static void EmitGetByteCountMethod(
        IndentedTextWriter writer,
        INamedTypeSymbol infoSymbol,
        ImmutableArray<IGroup> memberGroups
    )
    {
        var summedLength = memberGroups.Length switch
        {
            > 0 => string.Join(" + ", memberGroups.Select(x => x.GetVariableByteLength() ?? $"{x.ConstantByteLength}")),
            _ => "0",
        };
        writer.WriteLine("/// <inheritdoc />");
        var isPure = memberGroups.SelectMembers().All(x => x is IConstantMember);
        if (isPure)
            writer.WriteLine("[global::System.Diagnostics.Contracts.Pure]");
        else
            summedLength = $"checked({summedLength})";
        writer.WriteMultiLine(
            $"""
[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
{RoslynHelper.GetGeneratedVersionAttribute(fullNamespace: true)}
public int GetByteCount() => {summedLength};
"""
        );
    }

    private static void EmitWriteImplementationMethod(
        IndentedTextWriter writer,
        ImmutableArray<IGroup> memberGroups,
        bool littleEndian,
        List<UtilityData> utilities
    )
    {
        // Method start
        var methodNameEndianness = littleEndian ? "LittleEndian" : "BigEndian";
        writer.WriteMultiLine(
            $$"""
/// <inheritdoc />
{{RoslynHelper.GetGeneratedVersionAttribute(fullNamespace: true)}}
public bool TryWrite{{methodNameEndianness}}(global::System.Span<byte> destination) => TryWrite{{methodNameEndianness}}(destination, out _);
/// <inheritdoc />
{{RoslynHelper.GetGeneratedVersionAttribute(fullNamespace: true)}}
public bool TryWrite{{methodNameEndianness}}(global::System.Span<byte> destination, out int bytesWritten)
{
"""
        );
        writer.Indent++;
        writer.WriteLine("bytesWritten = 0;");
        writer.WriteEmptyLine();
        // All the members in the group
        foreach ((IGroup? memberInfoGroup, var index) in memberGroups.Select((group, i) => (group, i)))
        {
            var currentByteIndex = 0;
            if (memberInfoGroup is BinaryObjectMemberGroup binaryObjectsGroup)
            {
                var endianness = littleEndian ? "LittleEndian" : "BigEndian";
                var bytesWrittenVariable = $"{Prefix}bytesWritten{binaryObjectsGroup.MemberSymbol.Name}";
                var writeCall = binaryObjectsGroup.UseInterfaceDispatch
                    ? $"global::Darp.BinaryObjects.Generated.Utilities.TryWriteBinaryObject{endianness}(destination[{currentByteIndex}..], this.{binaryObjectsGroup.MemberSymbol.Name}, out var {bytesWrittenVariable})"
                    : $"this.{binaryObjectsGroup.MemberSymbol.Name}.TryWrite{endianness}(destination[{currentByteIndex}..], out var {bytesWrittenVariable})";
                writer.WriteLine($"if (!{writeCall})");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"bytesWritten += {bytesWrittenVariable};");
                writer.WriteLine("return false;");
                writer.Indent--;
                writer.WriteLine("}");
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"destination = destination[{bytesWrittenVariable}..];");
                }
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"destination = destination[{currentByteIndex}..];");
                }
                writer.WriteLine($"bytesWritten += {bytesWrittenVariable};");
                writer.WriteEmptyLine();
            }
            else if (memberInfoGroup is IVariableMemberGroup variableGroup)
            {
                if (
                    !variableGroup.TryGetWriteString(
                        littleEndian,
                        currentByteIndex,
                        out var writeString,
                        out var bytesWrittenString
                    )
                )
                {
                    continue;
                }

                writer.WriteMultiLine(writeString);
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"destination = destination[{bytesWrittenString}..];");
                }
                if (bytesWrittenString is not null)
                {
                    writer.WriteLine($"bytesWritten += {bytesWrittenString};");
                }
                writer.WriteEmptyLine();
            }
            else if (memberInfoGroup is ConstantBinaryMemberGroup constantGroup)
            {
                // Ensure length of destination
                var summedLength = memberInfoGroup.GetLengthCodeString();
                var memberChecks = constantGroup
                    .Members.Select(member =>
                        member switch
                        {
                            ConstantArrayMember array => $"{array.GetCollectionCount()} < {array.ArrayLength}",
                            ConstantWellKnownMember scalar => scalar.GetWriteOverflowCheck(),
                            _ => null,
                        }
                    )
                    .Where(check => check is not null);
                writer.WriteLine(
                    $"if (destination.Length < {summedLength}{string.Concat(memberChecks.Select(check => $" || {check}"))})"
                );
                writer.Indent++;
                writer.WriteLine("return false;");
                writer.Indent--;
                var countedByteIndex = 0;
                foreach (IConstantMember memberInfo in constantGroup.Members)
                {
                    if (
                        !memberInfo.TryGetWriteString(
                            littleEndian,
                            currentByteIndex,
                            out var writeString,
                            out var bytesWritten
                        )
                    )
                    {
                        continue;
                    }
                    var mayFail =
                        memberInfo.TypeKind is WellKnownTypeKind.BinaryObject
                        || memberInfo is ConstantArrayMember { IsNarrow: true };
                    if (mayFail && currentByteIndex > countedByteIndex)
                        writer.WriteLine($"bytesWritten += {currentByteIndex - countedByteIndex};");
                    writer.WriteMultiLine(writeString);
                    currentByteIndex += bytesWritten;
                    if (mayFail)
                    {
                        writer.WriteLine($"bytesWritten += {bytesWritten};");
                        countedByteIndex = currentByteIndex;
                    }
                }
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"destination = destination[{currentByteIndex}..];");
                }
                if (currentByteIndex > countedByteIndex)
                    writer.WriteLine($"bytesWritten += {currentByteIndex - countedByteIndex};");
                writer.WriteEmptyLine();
            }
        }

        // The end of the method
        writer.WriteLine("return true;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitReadImplementationMethod(
        IndentedTextWriter writer,
        INamedTypeSymbol symbol,
        ImmutableArray<IGroup> memberGroups,
        ImmutableArray<IMember> constructorParameters,
        bool littleEndian,
        List<UtilityData> utilities
    )
    {
        // Method start
        var methodNameEndianness = littleEndian ? "LittleEndian" : "BigEndian";

        var valueParameter = symbol.IsValueType
            ? $"out {symbol.Name}"
            : $"[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {symbol.Name}?";
        writer.WriteMultiLine(
            $$"""
/// <inheritdoc />
{{RoslynHelper.GetGeneratedVersionAttribute(fullNamespace: true)}}
public static bool TryRead{{methodNameEndianness}}(global::System.ReadOnlySpan<byte> source, {{valueParameter}} value) => TryRead{{methodNameEndianness}}(source, out value, out _);
/// <inheritdoc />
{{RoslynHelper.GetGeneratedVersionAttribute(fullNamespace: true)}}
public static bool TryRead{{methodNameEndianness}}(global::System.ReadOnlySpan<byte> source, {{valueParameter}} value, out int bytesRead)
{
"""
        );
        writer.Indent++;
        writer.WriteLine("bytesRead = 0;");
        if (memberGroups.Length > 0)
        {
            writer.WriteLine("value = default;");
        }
        writer.WriteEmptyLine();
        foreach ((IGroup? memberInfoGroup, var index) in memberGroups.Select((group, i) => (group, i)))
        {
            var currentByteIndex = 0;
            if (memberInfoGroup is BinaryObjectMemberGroup binaryObjectsGroup)
            {
                var endianness = littleEndian ? "LittleEndian" : "BigEndian";
                var variableName = $"{Prefix}read{binaryObjectsGroup.MemberSymbol.Name}";
                var bytesReadVariable = $"{Prefix}bytesRead{binaryObjectsGroup.MemberSymbol.Name}";
                var readCall = binaryObjectsGroup.UseInterfaceDispatch
                    ? $"global::Darp.BinaryObjects.Generated.Utilities.TryReadBinaryObject{endianness}<{binaryObjectsGroup.TypeSymbol.ToDisplayString()}>(source[{currentByteIndex}..], out var {variableName}, out var {bytesReadVariable})"
                    : $"{binaryObjectsGroup.TypeSymbol.ToDisplayString()}.TryRead{endianness}(source[{currentByteIndex}..], out var {variableName}, out var {bytesReadVariable})";
                writer.WriteLine($"if (!{readCall})");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"bytesRead += {bytesReadVariable};");
                writer.WriteLine("return false;");
                writer.Indent--;
                writer.WriteLine("}");
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"source = source[{bytesReadVariable}..];");
                }
                writer.WriteLine($"bytesRead += {bytesReadVariable};");
                writer.WriteEmptyLine();
            }
            else if (memberInfoGroup is IVariableMemberGroup arrayMemberInfo)
            {
                if (
                    !arrayMemberInfo.TryGetReadString(
                        littleEndian,
                        currentByteIndex,
                        out var readString,
                        out var bytesReadString
                    )
                )
                {
                    continue;
                }
                writer.WriteMultiLine(readString);
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"source = source[{bytesReadString}..];");
                }
                writer.WriteLine($"bytesRead += {bytesReadString};");
                writer.WriteEmptyLine();
            }
            else if (memberInfoGroup is ConstantBinaryMemberGroup constantGroup)
            {
                // Ensure length of source
                var summedLength = memberInfoGroup.GetLengthCodeString();
                writer.WriteLine($"if (source.Length < {summedLength})");
                writer.Indent++;
                writer.WriteLine("return false;");
                writer.Indent--;
                var countedByteIndex = 0;
                foreach (IConstantMember memberInfo in constantGroup.Members)
                {
                    if (
                        !memberInfo.TryGetReadString(
                            littleEndian,
                            currentByteIndex,
                            out var writeString,
                            out var bytesRead
                        )
                    )
                    {
                        continue;
                    }
                    if (memberInfo.TypeKind is WellKnownTypeKind.BinaryObject && currentByteIndex > countedByteIndex)
                        writer.WriteLine($"bytesRead += {currentByteIndex - countedByteIndex};");
                    writer.WriteMultiLine(writeString);
                    currentByteIndex += bytesRead;
                    if (memberInfo.TypeKind is WellKnownTypeKind.BinaryObject)
                    {
                        writer.WriteLine($"bytesRead += {bytesRead};");
                        countedByteIndex = currentByteIndex;
                    }
                }
                if (index != memberGroups.Length - 1)
                {
                    writer.WriteLine($"source = source[{currentByteIndex}..];");
                }
                if (currentByteIndex > countedByteIndex)
                {
                    writer.WriteLine($"bytesRead += {currentByteIndex - countedByteIndex};");
                    writer.WriteEmptyLine();
                }
            }
        }

        // Method end
        IEnumerable<string> constructorNames = constructorParameters.Select(x => $"{Prefix}read{x.MemberSymbol.Name}");
        writer.Write($"value = new {symbol.Name}({string.Join(", ", constructorNames)})");
        IMember[] objectInitializerMembers = memberGroups.SelectMembers().Except(constructorParameters).ToArray();
        if (objectInitializerMembers.Length > 0)
        {
            writer.WriteLine();
            writer.WriteLine("{");
            writer.Indent++;
            foreach (IMember x in objectInitializerMembers)
            {
                writer.WriteLine($"{x.MemberSymbol.Name} = {Prefix}read{x.MemberSymbol.Name},");
            }
            writer.Indent--;
            writer.Write("}");
        }
        writer.WriteLine(";");
        writer.WriteLine("return true;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitOptionalNamespaceEnd(IndentedTextWriter writer, INamedTypeSymbol symbol)
    {
        var typeNamespace = symbol.GetNamespace();
        if (string.IsNullOrWhiteSpace(typeNamespace))
            return;
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitUtilityClass(
        IndentedTextWriter writer,
        ImmutableArray<UtilityData> requestedUtilities,
        bool isInternal
    )
    {
        if (requestedUtilities.Length == 0)
        {
            return;
        }

        var modifier = isInternal ? "internal" : "file";
        writer.WriteLine(
            $$"""
namespace Darp.BinaryObjects.Generated
{
    using Darp.BinaryObjects;
    using System;
    using System.Buffers.Binary;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;

    /// <summary>Helper methods used by generated BinaryObjects.</summary>
    {{RoslynHelper.GetGeneratedVersionAttribute(false)}}
    {{modifier}} static class Utilities
    {
"""
        );
        writer.Indent++;
        writer.Indent++;
        foreach (var utilityData in requestedUtilities.OrderBy(x => x.TypeKind).ThenBy(x => x.CollectionKind))
        {
            (
                var isReadUtility,
                WellKnownCollectionKind collectionKind,
                WellKnownTypeKind typeKind,
                var constLength,
                var emitLittleAndBigEndian,
                var isNarrow
            ) = utilityData;
            if (isNarrow)
            {
                EmitNarrowUtility(writer, isReadUtility, collectionKind, typeKind);
                continue;
            }
            if (typeKind is WellKnownTypeKind.BinaryObject)
            {
                if (collectionKind is WellKnownCollectionKind.None)
                    EmitBinaryObjectScalarUtilities(writer, isReadUtility);
                else
                    EmitBinaryObjectCollectionUtilities(writer, collectionKind, isReadUtility);
                continue;
            }
            if (isReadUtility)
            {
                EmitReadUtility(writer, collectionKind, typeKind, constLength, emitLittleAndBigEndian);
            }
            else
            {
                EmitWriteUtility(writer, collectionKind, typeKind, emitLittleAndBigEndian);
            }
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitBinaryObjectScalarUtilities(IndentedTextWriter writer, bool generateRead)
    {
        writer.WriteMultiLine(
            generateRead
                ? """
public static bool TryReadBinaryObjectLittleEndian<T>(ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? value, out int bytesRead)
    where T : IBinaryReadable<T> => T.TryReadLittleEndian(source, out value, out bytesRead);
public static bool TryReadBinaryObjectBigEndian<T>(ReadOnlySpan<byte> source, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? value, out int bytesRead)
    where T : IBinaryReadable<T> => T.TryReadBigEndian(source, out value, out bytesRead);
"""
                : """
public static int GetBinaryObjectByteCount<T>(T value)
    where T : IBinaryWritable => value.GetByteCount();
public static bool TryWriteBinaryObjectLittleEndian<T>(Span<byte> destination, T value, out int bytesWritten)
    where T : IBinaryWritable => value.TryWriteLittleEndian(destination, out bytesWritten);
public static bool TryWriteBinaryObjectBigEndian<T>(Span<byte> destination, T value, out int bytesWritten)
    where T : IBinaryWritable => value.TryWriteBigEndian(destination, out bytesWritten);
"""
        );
    }
}
