<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Darp.BinaryObjects\Darp.BinaryObjects.csproj" />
    <ProjectReference Include="..\..\src\Darp.BinaryObjects.Generator\Darp.BinaryObjects.Generator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Resources\**\*.cs" />
    <EmbeddedResource Include="Resources\**\*.cs" />
  </ItemGroup>
</Project>
